In [ ]:
 l1 =  [5,3.14,"eds"]
print(l1)

[5, 3.14, 'eds']


In [ ]:
d1 = {"eds":10,"son":20,"dt":30}
print(d1)

{'eds': 10, 'son': 20, 'dt': 30}


In [ ]:
t1 = (54,3.14,"eds")
print(t1)

(54, 3.14, 'eds')


In [ ]:
a = 54
print("a as int:",a)

a as int: 54


b = 3.1416
print("b as long:",b)

In [ ]:
c = 12345
print("c as float:",c)

c as float: 12345


In [ ]:
str1 = "this is python"
print(str1)

this is python


In [ ]:
m1 = int(input())
m2 = int(input())
m3 = int(input())
if m1>m2 and m1>m3 :
  print(m1,"is greater")
if m2>m1 and m2>m3 :
  print(m2,"is greater")
if m3>m1 and m3>m2 :
  print(m3,"is greatermb")

22
25
27
27 is greater


In [ ]:
print("enter a number")
num = int(input())
if num%2==0:
  print("number is even")
else:
    print("number is odd")

enter a number
23
number is odd


In [ ]:
if n1>n2:
  if n1>n3:
    print(n1,"is largest")
if n2>n1:
  if n2>n3:
    print(n2,"is largest")
if n3>n1:
  if n3>n2:
    print(n3,"is largest")
print("main area ends")

NameError: ignored

In [ ]:
import pandas as pd
df = pd.read_excel('/content/Copy of EDS Excel Employe (116)(1).xlsx')
display(df)
df1 = pd.read_excel('/content/Copy of (116) Salary emp(1).xlsx')
print(df1)

Unnamed: 0 Unnamed: 1 Unnamed: 2           Unnamed: 3 Unnamed: 4
0      Sr no.   Emp Name     Emp id                 Date     Leaves
1           1    Ganesh        1001  2023-01-21 00:00:00          2
2           2     Kartik       1002  2023-01-22 00:00:00          4
3           3      Veera       1003  2023-01-23 00:00:00          8
4           4  Sanskruti       1004  2023-01-24 00:00:00          6
5           5    Archana       1005  2023-01-25 00:00:00          1
6           6   Aradhana       1006  2023-01-26 00:00:00          2
7           7    Pratham       1007  2023-01-27 00:00:00          3
8           8     Sayali       1008  2023-01-28 00:00:00          5
9           9     Smruti       1009  2023-01-29 00:00:00          9
10         10      Vijay       1010  2023-01-30 00:00:00          7

    Emp Name  Emp id  Salary
0    Ganesh     1001   25000
1     Kartik    1002   40000
2      Veera    1003   80000
3  Sanskruti    1004   60000
4    Archana    1005   50000
5   Aradhana    1006   30000
6    Pratham    1007   15000
7     Sayali    1008   55000
8     Smruti    1009   80000
9      Vijay    1010  100000


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
df1.sort_values(by=['Salary'])

Emp Name  Emp id  Salary
6    Pratham    1007   15000
0    Ganesh     1001   25000
5   Aradhana    1006   30000
1     Kartik    1002   40000
4    Archana    1005   50000
7     Sayali    1008   55000
3  Sanskruti    1004   60000
2      Veera    1003   80000
8     Smruti    1009   80000
9      Vijay    1010  100000

In [ ]:
df1.sort_values(by=['Salary'],ascending=False)

Emp Name  Emp id  Salary
9      Vijay    1010  100000
2      Veera    1003   80000
8     Smruti    1009   80000
3  Sanskruti    1004   60000
7     Sayali    1008   55000
4    Archana    1005   50000
1     Kartik    1002   40000
5   Aradhana    1006   30000
0    Ganesh     1001   25000
6    Pratham    1007   15000

In [ ]:
display(df,df1)

Unnamed: 0 Unnamed: 1 Unnamed: 2           Unnamed: 3 Unnamed: 4
0      Sr no.   Emp Name     Emp id                 Date     Leaves
1           1    Ganesh        1001  2023-01-21 00:00:00          2
2           2     Kartik       1002  2023-01-22 00:00:00          4
3           3      Veera       1003  2023-01-23 00:00:00          8
4           4  Sanskruti       1004  2023-01-24 00:00:00          6
5           5    Archana       1005  2023-01-25 00:00:00          1
6           6   Aradhana       1006  2023-01-26 00:00:00          2
7           7    Pratham       1007  2023-01-27 00:00:00          3
8           8     Sayali       1008  2023-01-28 00:00:00          5
9           9     Smruti       1009  2023-01-29 00:00:00          9
10         10      Vijay       1010  2023-01-30 00:00:00          7

Emp Name  Emp id  Salary
0    Ganesh     1001   25000
1     Kartik    1002   40000
2      Veera    1003   80000
3  Sanskruti    1004   60000
4    Archana    1005   50000
5   Aradhana    1006   30000
6    Pratham    1007   15000
7     Sayali    1008   55000
8     Smruti    1009   80000
9      Vijay    1010  100000

In [ ]:
df3 = pd.merge(df,df1)
df3

NameError: ignored

In [ ]:
def sal():
  import pandas as pd
  a = df1.sort_values(by=['Salary'],ascending=False)
  g = a.nlargest(5,'Salary','first')
  print(g)
  sal()

In [ ]:
#tupple operators
t1 = (10,20,30,"python",15.17)
t2 = (80.86,21,"atharva")
print(t1)
print(t2)

(10, 20, 30, 'python', 15.17)
(80.86, 21, 'atharva')


In [ ]:
#accessing tupple elements using indexing
print(t1[0])

10


In [ ]:
#navigate tupple index
print(t1[-1])
print(t2[-2])

15.17
21


In [ ]:
#itirating through tupples
for i in t1:
  print(i)

10
20
30
python
15.17


In [ ]:
#slicing tuples
st1 = t1[1:4]
print(st1)

(20, 30, 'python')


In [ ]:
#tupples are immutable
str2 = t1 +(50,60)
print(str2)

(10, 20, 30, 'python', 15.17, 50, 60)


In [ ]:
#finding length of tupple
str3 = t1.__len__()
print(str3)

5


In [ ]:
#membership operators
print(10 in t1)
print(10 not in t1)

True
False


In [ ]:
#concatinate tuple
t3 = t1 + t2
print(t3)

(10, 20, 30, 'python', 15.17, 80.86, 21, 'atharva')


In [ ]:
#multiplying tuple
t4 = t1*3
print(t4)

(10, 20, 30, 'python', 15.17, 10, 20, 30, 'python', 15.17, 10, 20, 30, 'python', 15.17)


In [ ]:
#deleting tupple
del t1

In [ ]:
T = "// try again //"
W = "// good to see you again //"
name = input("username=")
password = input("password=")
if password == "1234":
  if name == "atharva":
    print("you are now logged in"+W)
  else:print("INVALID USERNAME"+T)
else:print("INVALID PASSWORD"+T)

username=atharva
password=1234
you are now logged in// good to see you again //


In [ ]:
# Dictionary operations
dict1 = {"ABD":12345,"EFG":69}

In [ ]:
# print ictionary
print(dict1)

{'ABD': 12345, 'EFG': 69}


In [ ]:
#reteriving keys from dictionary
print(dict1.keys())

dict_keys(['ABD', 'EFG'])


In [ ]:
#reteriving values from dicitonary
print(dict1.values())

dict_values([12345, 69])


In [ ]:
#update dictionary
dict1.update({"XYZ":5-4-2004})
print(dict1)

{'ABD': 12345, 'EFG': 69, 'XYZ': -2003}


In [ ]:
#find length of dictionary
a = dict1.__len__()
print(a)

3


In [ ]:
dict1.pop("EFG")
print(dict1)

{}


In [ ]:
import pandas as pd
df = pd.read_csv('/content/Book1.csv')
print(df.values.tolist())

[['PLIER', 'SS001', 150, 80, 1234, nan], ['SCREW DRIVER', 'SS002', 230, 70, 2234, nan], ['NUT BOLTS', 'SS003', 145, 69, 1233, nan], ['WASHERS', 'SS004', 134, 79, 1245, nan], ['FILE', 'SS005', 123, 58, 123, nan], ['TESTERS', 'SS006', 253, 78, 123, nan], ['L KEYS', 'SS007', 123, 80, 133, nan], ['GRINDERS', 'SS008', 124, 90, 1333, nan], ['DRILL', 'SS009', 124, 80, 1223, nan], ['SCREWS', 'SS010', 123, 57, 2344, nan], ['SAFETY KIT', 'SS011', 134, 125, 3444, nan], ['SAND PAPER', 'SS012', 242, 180, 323, nan], ['FILTER PAPER', 'SS013', 123, 56, 23, nan], ['DRILL BITS', 'SS014', 113, 80, 123, nan], ['SQUARE NUTS', 'SS015', 134, 90, 1112, nan], ['FOIL', 'SS016', 133, 80, 1123, nan], ['CARDSHEET', 'SS017', 342, 90, 1331, nan], ['COLLECTOR', 'SS018', 134, 90, 2345, nan], ['FLASHLIGHTS', 'SS019', 70, 50, 3444, nan]]


In [ ]:
 #set theory
 s1 = {10,20,30}
 for i in s1:
  print(i)

10
20
30


In [ ]:
s1 = {10,20,30}
s1.add(5)
print(s1)

{10, 20, 5, 30}


In [ ]:
s1 = {10,20,30}
s1.update({1,3,7})
print(s1)

{1, 3, 20, 7, 10, 30}


In [ ]:
s1.discard(7)
print(s1)

{1, 3, 20, 10, 30}


In [ ]:
a={1,2,3,4,5}
b={5,6,7,8,9}
c=a|b
print(c)

{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [ ]:
i = a & b
print(i)

{5}


In [ ]:
i = a - b
print(i)

{1, 2, 3, 4}


In [ ]:
a = {10,20,30,50,80}
b = {10,30,40,50,60}
i = a ^ b
print(i)

{80, 20, 40, 60}


In [ ]:
s = {2,4,6,8,10}
s.clear()
print(s)

set()


In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
y = arr.view()
arr[1] = 42
arr[0] = 45
print(arr)
print(x)
print(y)

[45 42  3  4  5]
[1 2 3 4 5]
[45 42  3  4  5]


In [ ]:
import numpy as np
x = np.array([[5,4],[2,3]])
y = np.array([[6,7],[1,2]])

print("addition of matrix")
print(np.add(x,y))

print("subctraction of matrix")
print(np.subtract(x,y))

addition of matrix
[[11 11]
 [ 3  5]]
subctraction of matrix
[[-1 -3]
 [ 1  1]]


In [ ]:
l1 = np.matrix('1,2,3 ; 4,5,6 ; 7,8,9')
a = np.array(l1)
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(a.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
import json
emp_dict={ 'erp':"you",9:"erp",8.9:"python"}
print(emp_dict)

{'erp': 'you', 9: 'erp', 8.9: 'python'}


In [ ]:
def outer():
  print ("outer function")

  def inner():
    print("inner function")

    inner()

  outer()

In [ ]:
daily_goal = int(input("Enter your daily water intake goal (in liters): "))

total_intake = 0

while total_intake < daily_goal:

    intake = int(input("Enter your water intake for the day (in liters): "))

    total_intake += intake

    if total_intake < daily_goal:
        print("Don't forget to drink more water throughout the day!")

percent_complete = (total_intake / daily_goal)*100

print("Congratulations! You have reached your daily water intake goal of {0} liters.".format(daily_goal))
print("Your total water intake for the day was {0} liters.".format(total_intake))
print("You have completed {0:.2f}% of your daily water intake goal.".format(percent_complete))

Enter your daily water intake goal (in liters): 40
Enter your water intake for the day (in liters): 50
Congratulations! You have reached your daily water intake goal of 40 liters.
Your total water intake for the day was 50 liters.
You have completed 125.00% of your daily water intake goal.


In [ ]:
list1 = [1,2,3,4,5,6,7,8,9,10]
alternate = list1[::2]
even = list1[1:10:2]
print(alternate)
print(even)

[1, 3, 5, 7, 9]
[2, 4, 6, 8, 10]


In [ ]:
from datetime import date
today = date.today()
print (today)

2023-05-02


In [ ]:
import datetime
current_time = datetime.datetime.now()
print("the atributes of now( are : ")

print("year:",end = "")
print(current_time.year)

print("month:",end = "")
print(current_time.month)

print("day:",end ="")
print(current_time.day)

the atributes of now( are : 
year:2023
month:5
day:2


In [ ]:
  from datetime import date
  def calculate(dob)
  today = date.today()


total_water = 0
water_ml = int(input("enter amount of water consumed in mililiters:"))
total_water += water_ml/1000
print("you have consumed",total_water,"liters of water today")

In [ ]:
x = 3
y = 5

if x == y:
    print("x and y are equal")
else:
    print("x and y are not equal")

x and y are not equal


In [ ]:
x = 6
y = 7

if x != y:
    print("x and y are not equal")
else:
    print("x and y are equal")

x and y are not equal


In [ ]:
a = 10
b = 20
c = a + b
print (c)

30


In [ ]:
a = 10
b = 20
c = a-b
print(c)

-10


In [ ]:
a = 2
b = 4
c = a*b
print(c)

8


In [ ]:
a = 4
b = 2
c = b/a
print(c)

0.5


In [ ]:
import pandas as pd
df=pd.read_excel('/content/EDS Excel Employe (118).xlsx')
a = df

print(a.values.tolist())

df1 = pd.read_excel(r'/content/(116) Salary emp.xlsx')
l = list(df1.itertuples(index=False))

t1 = [tuple(x) for x in df1.values]

d1 = df.to_dict()

def freq(l):
  counter = 0
  num = l[0]
  for i in l:
    cf = l.count(i)
    counter = cf
    num = i
    return 0
    print(freq(l))

[['Sr no.', 'Emp Name', 'Emp id', 'Date', 'Leaves'], [1, 'Ganesh ', 1001, datetime.datetime(2023, 1, 21, 0, 0), 2], [2, 'Kartik', 1002, datetime.datetime(2023, 1, 22, 0, 0), 4], [3, 'Veera', 1003, datetime.datetime(2023, 1, 23, 0, 0), 8], [4, 'Sanskruti', 1004, datetime.datetime(2023, 1, 24, 0, 0), 6], [5, 'Archana', 1005, datetime.datetime(2023, 1, 25, 0, 0), 1], [6, 'Aradhana', 1006, datetime.datetime(2023, 1, 26, 0, 0), 2], [7, 'Pratham', 1007, datetime.datetime(2023, 1, 27, 0, 0), 3], [8, 'Sayali', 1008, datetime.datetime(2023, 1, 28, 0, 0), 5], [9, 'Smruti', 1009, datetime.datetime(2023, 1, 29, 0, 0), 9], [10, 'Vijay', 1010, datetime.datetime(2023, 1, 30, 0, 0), 7]]


In [ ]:
import math
print(math.pow(7,9))

40353607.0


In [ ]:
from itertools import count

for number in count(start=5, step=3):
    if number > 10:
       break
    print(number)

5
8


In [ ]:
x = range(3,10)
for n in x:
  print(n)

3
4
5
6
7
8
9


In [ ]:
from fractions import Fraction

print(Fraction(84,21))

print(Fraction(81,7))

print(Fraction(23,17))

4
81/7
23/17


In [ ]:
import decimal
float_division=22/7
decimal_division=decimal.Decimal(22)/decimal.Decimal(7)
print("Result for float division of 4 by 3:")
print(float_division)
print("Result for decimal division of 4 by 3:")
print(decimal_division)

Result for float division of 4 by 3:
3.142857142857143
Result for decimal division of 4 by 3:
3.142857142857142857142857143


In [ ]:
 import pandas as pd
 import numpy as np

 df = pd.read_excel('/content/Sales (1).xlsx',header=None)
 df1 = pd.read_excel('/content/Sales (1).xlsx',header=None)

 array = df.to_numpy()
 array1 = df1.to_numpy()

 print(array)
 print(array1)

FileNotFoundError: ignored

In [ ]:
print("addition of matrix")
print(np.add(array,array1))

addition of matrix
[['Product IDProduct ID' 'Product detailsProduct details'
  'Supplier DetailsSupplier Details' 'Customer DetailsCustomer Details'
  'GenderGender']
 ['P00001P00001' 'Lenovo LaptopLenovo Laptop' 'Raka Ele.Raka Ele.'
  'Kaustubh MahajanKaustubh Mahajan' 'MaleMale']
 ['P00002P00002' 'Samsung M31Samsung M31' 'Vijay SalesVijay Sales'
  'Siddhi KiwaleSiddhi Kiwale' 'FemaleFemale']
 ['P00003P00003' 'Realmi 10proRealmi 10pro' 'Gada Ele.Gada Ele.'
  'Sanket KandalkarSanket Kandalkar' 'MaleMale']
 ['P00004P00004' 'Oppo F21Oppo F21' 'Surya Ele.Surya Ele.'
  'Yash MaliYash Mali' 'MaleMale']
 ['P00005P00005' 'Lenovo LaptopLenovo Laptop' 'Raka Ele.Raka Ele.'
  'Yash BagulYash Bagul' 'MaleMale']
 ['P00006P00006' 'Samsung M31Samsung M31' 'Gada Ele.Gada Ele.'
  'Siddhi KiwaleSiddhi Kiwale' 'FemaleFemale']
 ['P00007P00007' 'LG TV 32"LG TV 32"' 'Vijay SalesVijay Sales'
  'Sanket KandalkarSanket Kandalkar' 'MaleMale']
 ['P00008P00008' 'Oppo F21Oppo F21' 'Surya Ele.Surya Ele.'
  'Kaustub

In [ ]:
matrix_length = len(array)
print(matrix_length)

21


In [ ]:
for i in range (matrix_length):
  print([i][-1])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [ ]:
print(array.T)

[['Product ID' 'P00001' 'P00002' 'P00003' 'P00004' 'P00005' 'P00006'
  'P00007' 'P00008' 'P00009' 'P00010' 'P00011' 'P00012' 'P00013' 'P00014'
  'P00015' 'P00016' 'P00017' 'P00018' 'P00019' 'P00020']
 ['Product details' 'Lenovo Laptop' 'Samsung M31' 'Realmi 10pro'
  'Oppo F21' 'Lenovo Laptop' 'Samsung M31' 'LG TV 32"' 'Oppo F21'
  'Lenovo Laptop' 'Samsung M31' 'LG TV 32"' 'Lenovo Laptop' 'Samsung M31'
  'Realmi 10pro' 'Lenovo Laptop' 'Oppo F21' 'LG TV 32"' 'Lenovo Laptop'
  'Samsung M31' 'LG TV 32"']
 ['Supplier Details' 'Raka Ele.' 'Vijay Sales' 'Gada Ele.' 'Surya Ele.'
  'Raka Ele.' 'Gada Ele.' 'Vijay Sales' 'Surya Ele.' 'Raka Ele.'
  'Gada Ele.' 'Surya Ele.' 'Raka Ele.' 'Surya Ele.' 'Raka Ele.'
  'Gada Ele.' 'Vijay Sales' 'Deshmukh sales' 'Raka Ele.' 'Deshmukh sales'
  'Gada Ele.']
 ['Customer Details' 'Kaustubh Mahajan' 'Siddhi Kiwale'
  'Sanket Kandalkar' 'Yash Mali' 'Yash Bagul' 'Siddhi Kiwale'
  'Sanket Kandalkar' 'Kaustubh Mahajan' 'Yash Mali' 'Siddhi Kiwale'
  'Sanket Kandalka

In [ ]:
array = array[:,array[0,:].argsort()]
print(array)

[['Customer Details' 'Gender' 'Product ID' 'Product details'
  'Supplier Details']
 ['Kaustubh Mahajan' 'Male' 'P00001' 'Lenovo Laptop' 'Raka Ele.']
 ['Siddhi Kiwale' 'Female' 'P00002' 'Samsung M31' 'Vijay Sales']
 ['Sanket Kandalkar' 'Male' 'P00003' 'Realmi 10pro' 'Gada Ele.']
 ['Yash Mali' 'Male' 'P00004' 'Oppo F21' 'Surya Ele.']
 ['Yash Bagul' 'Male' 'P00005' 'Lenovo Laptop' 'Raka Ele.']
 ['Siddhi Kiwale' 'Female' 'P00006' 'Samsung M31' 'Gada Ele.']
 ['Sanket Kandalkar' 'Male' 'P00007' 'LG TV 32"' 'Vijay Sales']
 ['Kaustubh Mahajan' 'Male' 'P00008' 'Oppo F21' 'Surya Ele.']
 ['Yash Mali' 'Male' 'P00009' 'Lenovo Laptop' 'Raka Ele.']
 ['Siddhi Kiwale' 'Female' 'P00010' 'Samsung M31' 'Gada Ele.']
 ['Sanket Kandalkar' 'Male' 'P00011' 'LG TV 32"' 'Surya Ele.']
 ['Kaustubh Mahajan' 'Male' 'P00012' 'Lenovo Laptop' 'Raka Ele.']
 ['Yash Mali' 'Male' 'P00013' 'Samsung M31' 'Surya Ele.']
 ['Siddhi Kiwale' 'Female' 'P00014' 'Realmi 10pro' 'Raka Ele.']
 ['Tanuja Mali' 'Female' 'P00015' 'Lenovo La

In [ ]:
array2 = array1.copy()
print(array2)

[['Product ID' 'Product details' 'Supplier Details' 'Customer Details'
  'Gender']
 ['P00001' 'Lenovo Laptop' 'Raka Ele.' 'Kaustubh Mahajan' 'Male']
 ['P00002' 'Samsung M31' 'Vijay Sales' 'Siddhi Kiwale' 'Female']
 ['P00003' 'Realmi 10pro' 'Gada Ele.' 'Sanket Kandalkar' 'Male']
 ['P00004' 'Oppo F21' 'Surya Ele.' 'Yash Mali' 'Male']
 ['P00005' 'Lenovo Laptop' 'Raka Ele.' 'Yash Bagul' 'Male']
 ['P00006' 'Samsung M31' 'Gada Ele.' 'Siddhi Kiwale' 'Female']
 ['P00007' 'LG TV 32"' 'Vijay Sales' 'Sanket Kandalkar' 'Male']
 ['P00008' 'Oppo F21' 'Surya Ele.' 'Kaustubh Mahajan' 'Male']
 ['P00009' 'Lenovo Laptop' 'Raka Ele.' 'Yash Mali' 'Male']
 ['P00010' 'Samsung M31' 'Gada Ele.' 'Siddhi Kiwale' 'Female']
 ['P00011' 'LG TV 32"' 'Surya Ele.' 'Sanket Kandalkar' 'Male']
 ['P00012' 'Lenovo Laptop' 'Raka Ele.' 'Kaustubh Mahajan' 'Male']
 ['P00013' 'Samsung M31' 'Surya Ele.' 'Yash Mali' 'Male']
 ['P00014' 'Realmi 10pro' 'Raka Ele.' 'Siddhi Kiwale' 'Female']
 ['P00015' 'Lenovo Laptop' 'Gada Ele.' 'Tanu

In [ ]:
array3 = array1.view()
print(array3)

[['Product ID' 'Product details' 'Supplier Details' 'Customer Details'
  'Gender']
 ['P00001' 'Lenovo Laptop' 'Raka Ele.' 'Kaustubh Mahajan' 'Male']
 ['P00002' 'Samsung M31' 'Vijay Sales' 'Siddhi Kiwale' 'Female']
 ['P00003' 'Realmi 10pro' 'Gada Ele.' 'Sanket Kandalkar' 'Male']
 ['P00004' 'Oppo F21' 'Surya Ele.' 'Yash Mali' 'Male']
 ['P00005' 'Lenovo Laptop' 'Raka Ele.' 'Yash Bagul' 'Male']
 ['P00006' 'Samsung M31' 'Gada Ele.' 'Siddhi Kiwale' 'Female']
 ['P00007' 'LG TV 32"' 'Vijay Sales' 'Sanket Kandalkar' 'Male']
 ['P00008' 'Oppo F21' 'Surya Ele.' 'Kaustubh Mahajan' 'Male']
 ['P00009' 'Lenovo Laptop' 'Raka Ele.' 'Yash Mali' 'Male']
 ['P00010' 'Samsung M31' 'Gada Ele.' 'Siddhi Kiwale' 'Female']
 ['P00011' 'LG TV 32"' 'Surya Ele.' 'Sanket Kandalkar' 'Male']
 ['P00012' 'Lenovo Laptop' 'Raka Ele.' 'Kaustubh Mahajan' 'Male']
 ['P00013' 'Samsung M31' 'Surya Ele.' 'Yash Mali' 'Male']
 ['P00014' 'Realmi 10pro' 'Raka Ele.' 'Siddhi Kiwale' 'Female']
 ['P00015' 'Lenovo Laptop' 'Gada Ele.' 'Tanu

In [ ]:
def buy_groceries(budget, price):
    if budget <= 500:
        if price <= budget/3:
            return "You can buy all three items."
        else:
            return "You cannot buy daily needs."
    else:
        if price <= 500/3:
            return "You can buy all three items."
        else:
            return "You cannot buy daily needs."

budget = 500
price = 200

result = buy_groceries(budget, price)
print(result)

You cannot buy daily needs.


In [ ]:
T = "// try again //"
W = "// good to see you again //"
name = input("username=")
password = input("password=")
if password == "1234":
  if name == "atharva":
    print("you are now logged in"+W)
  else:print("INVALID USERNAME"+T)
else:print("INVALID PASSWORD"+T)

daily_goal = int(input("Enter your daily water intake goal (in liters): "))

total_intake = 0

while total_intake < daily_goal:

    intake = int(input("Enter your water intake for the day (in liters): "))

    total_intake += intake

    percent_complete = (total_intake / daily_goal) * 100

    print("You have completed {0:.2f}% of your daily water intake goal.".format(percent_complete))

    if total_intake < daily_goal:
        print("Don't forget to drink more water throughout the day!")

print("Congratulations! You have reached your daily water intake goal of {0} liters.".format(daily_goal))
print("Your total water intake for the day was {0} liters.".format(total_intake))

username=atharva
password=1233
INVALID PASSWORD// try again //
Enter your daily water intake goal (in liters): 


ValueError: ignored

In [ ]:
#Atharva Dhamane
#112 PRN- 202201090001
#A-1

# FETCH DETAILS
df = pd.read_csv('/content/Book1.csv')
print(df)

# DISPLAY DATA INASCENDING ORDER WITH RESPECT TO AGE
df.sort_values(by=['AGE'],ascending=False)

    Sr No.    POLITICIAN NAMES   AGE PLACE OF BIRTH  PHONE NUMBER  \
0      1.0       Shubash singh  20.0          Nagar  6.963877e+09   
1      2.0       Charan Shetty  22.0           Pune  7.547931e+09   
2      3.0        Yogesh Reddy  34.0           Pune  8.983968e+09   
3      4.0           Raj Patil  35.0           Pune  9.869579e+09   
4      5.0       Shivraj Dubey  28.0             UP  9.897938e+09   
5      6.0         Rajeev Kale  42.0           Pune  8.697671e+09   
6      7.0       Tanmay Gaware  27.0           Pune  7.487608e+09   
7      8.0     Atharva Dhamane  29.0       Kolhapur  6.847834e+09   
8      9.0  Prathamesh Galande  32.0          Nagar  8.407605e+09   
9     10.0      Samarth Shinde  36.0        Solapur  4.648710e+09   
10    11.0       Narendra Modi  40.0         Gujrat  8.440978e+09   
11     1.0       Udhav Thakrey  47.0          Surat  5.309808e+09   
12    12.0       Rakesh Thorat  50.0         Satara  4.849868e+09   
13    13.0    Suyash Choudhary  22

Sr No.    POLITICIAN NAMES   AGE PLACE OF BIRTH  PHONE NUMBER  \
12    12.0       Rakesh Thorat  50.0         Satara  4.849868e+09   
11     1.0       Udhav Thakrey  47.0          Surat  5.309808e+09   
18    18.0     Bupendra Pilley  44.0          Latur  5.890751e+09   
5      6.0         Rajeev Kale  42.0           Pune  8.697671e+09   
10    11.0       Narendra Modi  40.0         Gujrat  8.440978e+09   
9     10.0      Samarth Shinde  36.0        Solapur  4.648710e+09   
3      4.0           Raj Patil  35.0           Pune  9.869579e+09   
2      3.0        Yogesh Reddy  34.0           Pune  8.983968e+09   
17    17.0        Sahil Musale  34.0          Ravet  4.587579e+09   
16    16.0      Pratik Morbale  33.0           Pune  7.468977e+09   
8      9.0  Prathamesh Galande  32.0          Nagar  8.407605e+09   
7      8.0     Atharva Dhamane  29.0       Kolhapur  6.847834e+09   
4      5.0       Shivraj Dubey  28.0             UP  9.897938e+09   
6      7.0       Tanmay Gaware  27.0           Pune  7.487608e+09   
15    15.0          Deep Patil  25.0         Jaipur  5.027979e+09   
19    19.0         Sagar Deore  24.0         Nashik  8.809689e+09   
14    14.0     Sandeep Waghere  24.0          Thane  8.758780e+09   
1      2.0       Charan Shetty  22.0           Pune  7.547931e+09   
13    13.0    Suyash Choudhary  22.0           Khed  6.983761e+09   
0      1.0       Shubash singh  20.0          Nagar  6.963877e+09   
20    20.0  Shantanu Bhaleroao  20.0           Pune  8.069867e+09   
21     NaN                 NaN   NaN            NaN           NaN   

   MARRIED STATUS  
12            yes  
11            yes  
18             no  
5             yes  
10             no  
9             yes  
3              no  
2              no  
17             no  
16           yes   
8              no  
7              no  
4             yes  
6              no  
15             no  
19            yes  
14             no  
1              no  
13            yes  
0             yes  
20             no  
21            NaN

In [ ]:
#CONVERT TO ARRAY
import pandas as pd
import numpy as np

df1 = pd.read_csv('/content/Book1.csv',header=None)

array = df1.to_numpy()

print(array)

[['Sr No.' 'POLITICIAN NAMES' 'AGE' 'PLACE OF BIRTH' 'PHONE NUMBER'
  'MARRIED STATUS']
 ['1' 'Shubash singh' '20' 'Nagar' '6963876784' 'yes']
 ['2' 'Charan Shetty' '22' 'Pune' '7547930967' 'no']
 ['3' 'Yogesh Reddy' '34' 'Pune' '8983968088' 'no']
 ['4' 'Raj Patil' '35' 'Pune' '9869578695' 'no']
 ['5' 'Shivraj Dubey' '28' 'UP' '9897937853' 'yes']
 ['6' 'Rajeev Kale' '42' 'Pune' '8697670709' 'yes']
 ['7' 'Tanmay Gaware' '27' 'Pune' '7487607889' 'no']
 ['8' 'Atharva Dhamane' '29' 'Kolhapur' '6847834070' 'no']
 ['9' 'Prathamesh Galande' '32' 'Nagar' '8407604790' 'no']
 ['10' 'Samarth Shinde' '36' 'Solapur' '4648709898' 'yes']
 ['11' 'Narendra Modi' '40' 'Gujrat' '8440978457' 'no']
 ['1' 'Udhav Thakrey' '47' 'Surat' '5309808087' 'yes']
 ['12' 'Rakesh Thorat' '50' 'Satara' '4849867897' 'yes']
 ['13' 'Suyash Choudhary' '22' 'Khed' '6983760789' 'yes']
 ['14' 'Sandeep Waghere' '24' 'Thane' '8758779754' 'no']
 ['15' 'Deep Patil' '25' 'Jaipur' '5027978954' 'no']
 ['16' 'Pratik Morbale' '33' 'Pun

In [ ]:
matrix_length = len(array)
print(matrix_length)

23


In [ ]:
for i in range (matrix_length):
  print([i][-1])

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22


In [ ]:
print(array.T)

[['Sr No.' '1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' '1' '12' '13'
  '14' '15' '16' '17' '18' '19' '20' nan]
 ['POLITICIAN NAMES' 'Shubash singh' 'Charan Shetty' 'Yogesh Reddy'
  'Raj Patil' 'Shivraj Dubey' 'Rajeev Kale' 'Tanmay Gaware'
  'Atharva Dhamane' 'Prathamesh Galande' 'Samarth Shinde' 'Narendra Modi'
  'Udhav Thakrey' 'Rakesh Thorat' 'Suyash Choudhary' 'Sandeep Waghere'
  'Deep Patil' 'Pratik Morbale' 'Sahil Musale' 'Bupendra Pilley'
  'Sagar Deore' 'Shantanu Bhaleroao' nan]
 ['AGE' '20' '22' '34' '35' '28' '42' '27' '29' '32' '36' '40' '47' '50'
  '22' '24' '25' '33' '34' '44' '24' '20' nan]
 ['PLACE OF BIRTH' 'Nagar' 'Pune' 'Pune' 'Pune' 'UP' 'Pune' 'Pune'
  'Kolhapur' 'Nagar' 'Solapur' 'Gujrat' 'Surat' 'Satara' 'Khed' 'Thane'
  'Jaipur' 'Pune' 'Ravet' 'Latur' 'Nashik' 'Pune' nan]
 ['PHONE NUMBER' '6963876784' '7547930967' '8983968088' '9869578695'
  '9897937853' '8697670709' '7487607889' '6847834070' '8407604790'
  '4648709898' '8440978457' '5309808087' '4849867897' '69

In [ ]:
array = array[:,array[0,:].argsort()]
print(array)

NameError: ignored

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Hobby.csv')
b = pd.DataFrame(df)
print(b)

   SR NO. NAME TYPE OF SWIMMER  AGE  EXPERIENCE(YEARS)
0       1   AA       Freestyle   17                  2
1       2   BB      Backstroke   14                  3
2       3   CC         Gliding   15                  4
3       4   DD      Sidestroke   18                  6
4       5   EE       Butterfly   19                  5
5       6   FF      Individual   11                  1
6       7   GG      Dolfinkick   12                  1
7       8   HH  Treading water   13                  2
8       9   II      Elementary   16                  3
9      10   JJ    Professional   20                  7


In [ ]:
a = df['TYPE OF SWIMMER']
print(a)

0         Freestyle
1        Backstroke
2           Gliding
3        Sidestroke
4         Butterfly
5        Individual
6        Dolfinkick
7    Treading water
8        Elementary
9      Professional
Name: TYPE OF SWIMMER, dtype: object


In [ ]:
print(b[['NAME','AGE']])
g = df.columns.tolist()
print(g)

  NAME  AGE
0   AA   17
1   BB   14
2   CC   15
3   DD   18
4   EE   19
5   FF   11
6   GG   12
7   HH   13
8   II   16
9   JJ   20
['SR NO.', 'NAME', 'TYPE OF SWIMMER', 'AGE', 'EXPERIENCE(YEARS)']


In [ ]:
z = df['NAME'].value_counts()
print(z)

AA    1
BB    1
CC    1
DD    1
EE    1
FF    1
GG    1
HH    1
II    1
JJ    1
Name: NAME, dtype: int64


In [ ]:
x = df['SR NO.'].value_counts()[1]
print(x)

1


In [ ]:
s = df.sort_values(by = 'EXPERIENCE(YEARS)',ascending=True)
print(s)

   SR NO. NAME TYPE OF SWIMMER  AGE  EXPERIENCE(YEARS)
5       6   FF      Individual   11                  1
6       7   GG      Dolfinkick   12                  1
0       1   AA       Freestyle   17                  2
7       8   HH  Treading water   13                  2
1       2   BB      Backstroke   14                  3
8       9   II      Elementary   16                  3
2       3   CC         Gliding   15                  4
4       5   EE       Butterfly   19                  5
3       4   DD      Sidestroke   18                  6
9      10   JJ    Professional   20                  7


In [ ]:
import pandas as pd
df = pd.read_csv('/content/Hobby.csv')
display(df)
df1 = pd.read_csv('/content/Hobby2.csv')
display(df1)

SR NO. NAME TYPE OF SWIMMER  AGE  EXPERIENCE(YEARS)
0       1   AA       Freestyle   17                  2
1       2   BB      Backstroke   14                  3
2       3   CC         Gliding   15                  4
3       4   DD      Sidestroke   18                  6
4       5   EE       Butterfly   19                  5
5       6   FF      Individual   11                  1
6       7   GG      Dolfinkick   12                  1
7       8   HH  Treading water   13                  2
8       9   II      Elementary   16                  3
9      10   JJ    Professional   20                  7

SR NO NAME   PHONE NO.
0      1   AA  8673847096
1      2   BB  7039709309
2      3   CC  8474876094
3      4   DD  9679868656
4      5   EE  3885993797
5      6   FF  4598656987
6      7   GG  3984637473
7      8   HH  6487259764
8      9   II  7468764984
9     10   JJ  7584372974

In [ ]:
import pandas as pd
df = pd.read_csv('/content/Hobby2.csv')
print(df.values.tolist())

[[1, 'AA', 8673847096], [2, 'BB', 7039709309], [3, 'CC', 8474876094], [4, 'DD', 9679868656], [5, 'EE', 3885993797], [6, 'FF', 4598656987], [7, 'GG', 3984637473], [8, 'HH', 6487259764], [9, 'II', 7468764984], [10, 'JJ', 7584372974]]


In [ ]:
df3 = pd.merge(df,df1)
display(df3)

SR NO. NAME TYPE OF SWIMMER  AGE  EXPERIENCE(YEARS)  SR NO   PHONE NO.
0       1   AA       Freestyle   17                  2      1  8673847096
1       2   BB      Backstroke   14                  3      2  7039709309
2       3   CC         Gliding   15                  4      3  8474876094
3       4   DD      Sidestroke   18                  6      4  9679868656
4       5   EE       Butterfly   19                  5      5  3885993797
5       6   FF      Individual   11                  1      6  4598656987
6       7   GG      Dolfinkick   12                  1      7  3984637473
7       8   HH  Treading water   13                  2      8  6487259764
8       9   II      Elementary   16                  3      9  7468764984
9      10   JJ    Professional   20                  7     10  7584372974

In [ ]:
df1.sort_values(by=['PHONE NO.'])

SR NO NAME   PHONE NO.
4      5   EE  3885993797
6      7   GG  3984637473
5      6   FF  4598656987
7      8   HH  6487259764
1      2   BB  7039709309
8      9   II  7468764984
9     10   JJ  7584372974
2      3   CC  8474876094
0      1   AA  8673847096
3      4   DD  9679868656

In [ ]:
df1.sort_values(by=['PHONE NO.'],ascending=False)

SR NO NAME   PHONE NO.
3      4   DD  9679868656
0      1   AA  8673847096
2      3   CC  8474876094
9     10   JJ  7584372974
8      9   II  7468764984
1      2   BB  7039709309
7      8   HH  6487259764
5      6   FF  4598656987
6      7   GG  3984637473
4      5   EE  3885993797